### ISSUE TITLE
[Prpopsal] Added yurtpvcdaemon & yurtpvc to support multi-site distribution of pvc resources

### ISSUE THREAD

**Issue by theonefx** [openyurtio/openyurt#1236]
# scenario
When deploying application process, we use `yurtappset` or `yurtappdaemon` for multiple sites distribution.
Its essence is applying `deployment` and `statefulset` resources to cluster, just by the controller to help create them.
But when business applications have persistence requirements, some problems arise:
- If we using `statefulset`, the `volumeClaimTemplates` property can create pvc automatically. This will achieve our goal.
- If we using `deployment`, there is currently no tool to help users automatically create the corresponding pvc for `deployment`.

# solution
## solution1
Provides a set of PVC-oriented CRDS and Controllers to help create pvc resources.
Temporarily named YurtPVCSet & YurtPVCDaemon.

## solution2
Provides a set of CRDS and controllers for common resources.
Temporarily named YurtResourceSet, YurtResourceDaemon.

**Comment by huiwq1990** [comment]
It's a feature like https://github.com/kubernetes/kubernetes/issues/93019 .

**Comment by rambohe-ch** [comment]
There is the same requirement from @LaurenceLiZhixin in #1185 , and i am afraid that we also need to consider the case that  how to use multiple pvc in one NodePool(or Deployment)?

**Comment by rambohe-ch** [comment]
In order to support pvc in multiple regions, think we need to solve two problems as following:
1. YurtAppDaemon can support to reference different pvc for different NodePool's workloads.
2. How to distribute multiple pvc resources in the cluster.

**Comment by rambohe-ch** [comment]
@theonefx @LaurenceLiZhixin As we discussed in the OpenYurt community meeting, the conclusion are as following:

> 1. YurtAppDaemon can support to reference different pvc for different NodePool's workloads.

we will add a new CRD resource like `ClusterRoleBinding` for defining the relationship between workload(like pods) and configuration resource(like pvc, configmap, secret, etc.), and webhook will be added for updating volumes/volumeMounts of workloads in terms of CRD setting.

The design of the new CRD will be  posted in a new proposal in the near future.

> 2. How to distribute multiple pvc resources in the cluster.

we will add a new CRD and controller in order to distribute pvc resource for every NodePool, and pvc will be created or deleted by the changes of NodePools.

The design of the new CRD will be  posted in a new proposal in the near future.

**Comment by rambohe-ch** [comment]
@theonefx this feature that i named as multi-regions configuration rendering engine will be taken by OSPP 2023, and issue #1435 is tracking this feature. so i think we can close this issue now.
