### ISSUE TITLE
UnitedDeployment usages

### ISSUE THREAD

**Issue by hle2** [openyurtio/openyurt#124]
Would like to understand how UnitedDeployment can be used?
1. How Subset used to select a group of Node (e.g. NodePool Name)? Does it define a NodePool CRD first?
2. if need to deploy 2 deployments (with different deploymentTemplate) in same Unit, How to define the UnitedDeployment? Is there any sample for reference? Thanks!

**Comment by kadisi** [comment]
@hle2  good idea, 

In the edge scenario, the distribution of worker nodes is relatively scattered. There may only be one worker node at the same physical location, and there may also be multiple worker nodes at the same physical location. However, multiple worker nodes are differentiated in OS, CPU architecture or network. Therefore, from the work Node resource perspective of edge nodes, they need to be divided into different Nodepool to represent the same set of features. All under the same nodepool node should have the same label, the annotation and taint, so k8s native resources (deployment, statefulset daemonset) easy deployment.

In order to enable k8s native Deployment, Statefulset,daemonset resources to deploy intelligently according to NodePool, we abstract the concept of UnitedDeployment which is a k8s crd. In the definition of UnitedDeployment, we support deployment, Daemonset, statefulSet resources can deploy to different Nodepool in one model.


@charleszheng44  and  I are working on it  and will submit a proposal later.

**Comment by hle2** [comment]
@kadisi, Thanks much for the comments! 
BTW, Does NoodPool is also defined as a CRD? If yes, does it in github now? Thanks!

**Comment by kadisi** [comment]
> @kadisi, Thanks much for the comments!
> BTW, Does NoodPool is also defined as a CRD? If yes, does it in github now? Thanks!

yes, NodePool is also defined as a CRD, we will later add a `yurtunit-manager` operator to manage both the `NodePool` and `UnitedDeployment` CRDS. At present, it is not in github. We will submit a proposal first, and we can discuss it in the community meeting. Eventually we will open source this part of the code。

**Comment by rambohe-ch** [comment]
@hle2 UnitedDeployment has been released, and the repo is here: https://github.com/openyurtio/yurt-app-manager
I will close this issue because not active for more than two months. if you have any other questions about `UnitedDeployment`, please open a new issue.

**Comment by hle2** [comment]
@rambohe-ch thanks much for the information!
