### ISSUE TITLE
[Prpopsal] New Product help data transmited from the edge to the cloud

### ISSUE THREAD

**Issue by theonefx** [openyurtio/openyurt#1407]
# scenario
First, openyurt is a control-plane product. However, in production practice, we often encounter many data-plane requirements.
Here's a typical scenario:
The customer is an energy enterprise that uses a node pool to manage a large number of professional devices. Even in a node pool, many devices of the same or different types exist.
These devices/bizapp are constantly generating run logs that are similar in structure but are generated frequently.
Users need to be able to obtain these data in the cloud side, but the user's cloud-edge network condition is not good, resulting in a lot of data transmission problems:
- Too many connections cause that the center cannot carry the load
- Data transfer timeout
- A transmission error was reported due to intermittent network interruption.
- Some large files never transfer to the central side
- Network traffic charges are too high

Now, abstracting this scenario again, we can get the requirements as follows:
- Users have a lot of data on the edge side that needs to be transferred to the cloud side
- These data do not require high real-time performance
- This data may be single large data (such as packets of tens of GB) or large amounts of small data (such as operation logs, monitoring, structured analysis results, etc.).
- The network between cloud edges of users has many restrictions, including but not limited to: intermittent network interruption, limited network bandwidth, and unidirectional network visibility

So, I proposed designing a data-facing product to solve the problem of transferring data from the edge to the cloud in an edge scenario.
The architecture looks like this:
![image](https://user-images.githubusercontent.com/3760138/233831509-25a753aa-1285-4bb0-a827-a511851b0083.png)

**Comment by zzguang** [comment]
We had a short meeting to discuss the possibility of integrating this solution with raven, and some temporary conclusions are listed below:
1. It seems more like a data cache/forward middleware solution, it ensures the data transferring reliability even in the unstable cloud edge network environment.
2. It should be de-coupled from raven logic, it focuses on the app data transferring while raven focuses on cloud edge network connection. It should be deployed separately, but it depends on raven to create the connection between cloud and edge at most usage scenarios.
3. Whether to put the related code implementation into raven repo is TBD, we don't prefer to create a new repo for it at current stage.
4. An updated proposal with more details will be submitted by @theonefx later, so that we can nail down the final solution based on it.

**Comment by fujitatomoya** [comment]
> It seems more like a data cache/forward middleware solution, it ensures the data transferring reliability even in the unstable cloud edge network environment.

agree, raven or openyurt cannot know how/what the application want to cache the data or anything like that. probably raven should be agnostic from this, meaning the use case makes sense but decoupling from raven design.

> An updated proposal with more details will be submitted by @theonefx later, so that we can nail down the final solution based on it.

whether this is one of the scope for raven or not, as common problem, i am interested in this discussion.

@theonefx @zzguang thank you very much for sharing insights.

**Comment by rambohe-ch** [comment]
@theonefx @fujitatomoya This feature will be covered by a newly added component named yurt-express, and the proposal of yurt-express is here: https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20231205-yurt-express.md

so i will close this issue and you can feel free to open or create new issues.

**Comment by fujitatomoya** [comment]
@rambohe-ch thanks for letting me know that!
