### ISSUE TITLE
fail to acquire lock configmap/yurtctl-lock

### ISSUE THREAD

**Issue by luhaopei** [openyurtio/openyurt#141]
执行完./yurtctl convert --provider minikube，
报如下错误：fail to convert kubernetes to yurt: fail to acquire lock configmap/yurtctl-lock

**Comment by rambohe-ch** [comment]
@BearLu thank you for filing issue.
would you upload your k8s version and os info, and any other useful message?

**Comment by BearLu** [comment]
K8s 1.19.4, ubuntu 18.04

**Comment by charleszheng44** [comment]
@BearLu In order to prevent multiple processes from converting the cluster at the same time, we use a configmap as the global lock to ensure that there is only one convertion going on on the cluster. The default timeout of the global lock is 5 minutes, so you can try to run the `yurtctl convert` again after the timeout.
