### ISSUE TITLE
[BUG] Missing yurt-app-manager repo

### ISSUE THREAD

**Issue by batthebee** [openyurtio/openyurt#1411]
**What happened**:

The yurt-app-manager repo doesnt exist anymore. We are currently trying to set up openyurt 1.2.1, which then no longer works. Can you just archive this for compatibility and leave it available? 

Thanks!

/kind bug

**Comment by Congrool** [comment]
agree +1, @rambohe-ch I think it's better to archive yurt-app-manager and some other repos instead of making them private.

**Comment by rambohe-ch** [comment]
@batthebee I had changed the visibility of yurt-app-manager from public to private, because controllers and webhooks(except yurtingress) have been migrated into yurt-manager component in openyurtio/openyurt repo.
I agree with the suggestion from @Congrool , i will go to archive the yurt-app-manager instead of changing visibility.
