### ISSUE TITLE
[Question] how to get bootstrap token?

### ISSUE THREAD

**Issue by song0071000** [openyurtio/openyurt#1529]
**What happened**:
`$ _output/local/bin/linux/amd64/yurtadm join 1.2.3.4:6443 --token=zffaj3.a5vjzf09qn9ft3gt --node-type=edge --discovery-token-unsafe-skip-ca-verification --v=5`

how or where can i get the token of yurtadm join command ?
I found i cannot get bootstrap token from public cloud k8s.

what i have tried:
i use kubeadm to create token
`kubeadm token`
After that, i get a token. 
Then use this token to join, but get this error:
`
I0608 14:24:01.749863    2856 token.go:230] [discovery] kube client is nil, use bootstrap config(&{  {false map[]} map[kubernetes:0xc000348c00] map[] map[token-bootstrap-client@kubernetes:0xc0002df4f0] token-bootstrap-client@kubernetes map[]}) to create client
I0608 14:24:01.975485    2856 token.go:243] [discovery] Failed to request cluster-info, will try again: Unauthorize
`
does something wrong?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by YTGhost** [comment]
Currently `yurtadm join` is based on the kubeadm binary, and the bootstrap token used is also obtained through the `kubeadm token` command

For the problem you're having, I wonder if it's because you're still using the token created at `kubeadm init`, which has a default expiration date of 24 hours, so maybe the token was already expired when you were using it.

My suggestion is to use the `kubeadm token create --print-join-command` to create a new token. If this is still a problem, you are welcome to continue to comment in this issue
