### ISSUE TITLE
[feature request]all resources can be cached by yurt-hub

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#162]
**What would you like to be added**:
only resources in the [resourceToKindMap](https://github.com/alibaba/openyurt/blob/master/pkg/yurthub/cachemanager/cache_manager.go#L46) can be cached by yurt-hub component, and this a limitation. yurt-hub should cache all kubernetes resources, including crd resource that defined by user.

**Why is this needed**:
when network between cloud and edge disconnected, if any pod(eg: calico) on the edge node that used some resources(like crd) not in the above map want to run continuously, that is to say, the pod can not restarted successfully because resources(like crd) are not cached by yurt-hub.

**Comment by vincent-pli** [comment]
@rambohe-ch 
Does this means we do not need to keep the list for cache all the resources?

**Comment by rambohe-ch** [comment]
> @rambohe-ch
> Does this means we do not need to keep the list for cache all the resources?

@vincent-pli  yeah,   the list([resourceToKindMap](https://github.com/alibaba/openyurt/blob/master/pkg/yurthub/cachemanager/cache_manager.go#L46)) will not be used to verify the resource that can be cached or not.

**Comment by GsssC** [comment]
We use resourceToKindMap is because the obj misses the field of apiverison and kind.

The reason why obj misses the field of apiverison and kind is yurthub using [serializer.WithoutConversionCodecFactory](https://github.com/alibaba/openyurt/blob/7095962687e2666a27d14e436b96ef893b228beb/pkg/yurthub/kubernetes/serializer/serializer.go#L48) as NegotiatedSerializer, which produces [WithoutVersionDecoder ](https://github.com/kubernetes/kubernetes/blob/994b5c6cc20bda188ac9bc33217f2dbc7ecf45bb/staging/src/k8s.io/apimachinery/pkg/runtime/helper.go#L256)and remove the apiversion/kind of object when serialized from http.resp.

Change the NegotiatedSerializer may solve.

@qclc (Chen Tao) how about dig more to find a WithVersionCodecFactory as NegotiatedSerializer?

@rambohe-ch PTAL.

**Comment by rambohe-ch** [comment]
> We use resourceToKindMap is because the obj misses the field of apiverison and kind.
> 
> The reason why obj misses the field of apiverison and kind is yurthub using [serializer.WithoutConversionCodecFactory](https://github.com/alibaba/openyurt/blob/7095962687e2666a27d14e436b96ef893b228beb/pkg/yurthub/kubernetes/serializer/serializer.go#L48) as NegotiatedSerializer, which produces [WithoutVersionDecoder ](https://github.com/kubernetes/kubernetes/blob/994b5c6cc20bda188ac9bc33217f2dbc7ecf45bb/staging/src/k8s.io/apimachinery/pkg/runtime/helper.go#L256)and remove the apiversion/kind of object when serialized from http.resp.
> 
> Change the NegotiatedSerializer may solve.
> 
> @qclc (Chen Tao) how about dig more to find a WithVersionCodecFactory as NegotiatedSerializer?
> 
> @rambohe-ch PTAL.

@GsssC i think it is a good answer, and i am look forward to your proposal @qclc

**Comment by GsssC** [comment]
@rambohe-ch yeah，besides，client-go scheme do not support decode cr request，we do need a specially designed nogotiatedSerializer to offer serializer(indeed, a json serializer) for cr req.

**Comment by qclc** [comment]
I added WithVersionCodecFactory instead of [serializer.WithoutConversionCodecFactory](https://github.com/alibaba/openyurt/blob/7095962687e2666a27d14e436b96ef893b228beb/pkg/yurthub/kubernetes/serializer/serializer.go#L48). Solved the issue of GVK information loss when decoding built-in resources. 
This PR extends the ability to cache CR resources, removing the restriction that only resources in [resourceToKindMap](https://github.com/openyurtio/openyurt/blob/4d7463a40801c29d09c4f7d10ba46b73cb019915/pkg/yurthub/cachemanager/cache_manager.go#L46) and [resourceToListKindMap](https://github.com/openyurtio/openyurt/blob/4d7463a40801c29d09c4f7d10ba46b73cb019915/pkg/yurthub/cachemanager/cache_manager.go#L62) can be cached, but the general serialization and deserialization capabilities for CR resources are still under development. 
The PR is in #225 , please review my code, and give some suggestions. @rambohe-ch @GsssC  
I will submit the corresponding proposal later to show how to encode and decode general CR resources to achieve the purpose of caching CR resources.
