### ISSUE TITLE
[feature request] Add yurtappset's support for statefulset

### ISSUE THREAD

**Issue by vie-serendipity** [openyurtio/openyurt#1966]
**What would you like to be added**:
Now YurtAppSet v1beta1 only support the dispatch of deployment workload. So related implementation of statefulset should be added according to the implementation of deployment workload.

**Why is this needed**:
In application management, statefulset workload is also common. In the former alpha version, yurtappset manages deployment and statefulset, which should carry over in the beta version.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@vie-serendipity Thanks for raising the issue. I think that support statefulset in yurtappset is not so eager, how about wait some feedbacks from the community before completing this feature.

the reason is that yurtappset v1beta1 started to ready on OpenYurt v1.4.0, we need to get more feedback from end users before we support more workloads in the yurtappset. and make sure that YurtAppSet v1beta1 is walking in a correct way.
