### ISSUE TITLE
[Question]when helm install yurt-app-manager, I get the error of bad certificate

### ISSUE THREAD

**Issue by cuiHL** [openyurtio/openyurt#1989]
<img width="1663" alt="image" src="https://github.com/openyurtio/openyurt/assets/26169306/41c43252-5fb0-48f3-9713-51cfee0de8fb">

**Comment by cuiHL** [comment]
> @cuiHL Thanks for raising the issue. would you like to write the details version and yaml files of yurt-manager?

the version of yurt-manager is v1.4.0
the used yaml is the same as https://github.com/openyurtio/openyurt-helm/tree/main/charts/yurt-manager
apart from yurt-manager  values.yaml
<img width="716" alt="image" src="https://github.com/openyurtio/openyurt/assets/26169306/ab91f7c3-48f2-458e-b33e-258c031e73fe">

**Comment by rambohe-ch** [comment]
@cuiHL It seems that you have used a customized yurt-manager helm chart, because the service name of yurt-manager webhook is `yurt-manager-webhook-service`, not `yurt-app-manager-webhook-service`.

https://github.com/openyurtio/openyurt/blob/e2d6795bde2355a86da24e7dc8231efd874c1b2b/charts/yurt-manager/templates/yurt-manager.yaml#L45

**Comment by cuiHL** [comment]
> @cuiHL It seems that you have used a customized yurt-manager helm chart, because the service name of yurt-manager webhook is `yurt-manager-webhook-service`, not `yurt-app-manager-webhook-service`.
> 
> https://github.com/openyurtio/openyurt/blob/e2d6795bde2355a86da24e7dc8231efd874c1b2b/charts/yurt-manager/templates/yurt-manager.yaml#L45

I get it

**Comment by cuiHL** [comment]
delete old crd resource and reinstall
