### ISSUE TITLE
a potential security risk 

### ISSUE THREAD

**Issue by HouqiyuA** [openyurtio/openyurt#2018]
We have recently discovered a potential security risk, and we would like to report it to you and provide relevant details so that you can take appropriate measures to address and improve it. We have already sent the specific details to your private email at [openyurt@gmail.com](mailto:openyurt@gmail.com).Looking forward to your reply！

**Comment by rambohe-ch** [comment]
@HouqiyuA  Thanks for raising the issue. There are some problems about mail address: [security@mail.openyurt.io](mailto:security@mail.openyurt.io), and the mail address for security disclosure is changed to: [kubernetes-security@service.aliyun.com](mailto:kubernetes-security@service.aliyun.com).

and this mail address upgrade will be fixed in this pull request: https://github.com/openyurtio/openyurt/pull/2026

would you like to transfer the mail to the address: [kubernetes-security@service.aliyun.com](mailto:kubernetes-security@service.aliyun.com) ?

Thank you in advance.

From @rambohe-ch
