### ISSUE TITLE
About OpenYurt RoadMap, whole picture design and long-term plan. 

### ISSUE THREAD

**Issue by Walnux** [openyurtio/openyurt#224]
It is good that OpenYurt 0.4.0 RoadMap was released out. The planned features are quite attractive.
However, I believe It will be better if the detailed feature description or design can also be opened and tracked through Github issues. so the community can know more detail on what is ongoing, and that is easier for people to involve in the project.
And another suggestion is that we even can start with the discussion on the future release plan basing on the whole picture of and the long time plan. I think that is quite important for the long-term development of the opensource project.  :)

**Comment by charleszheng44** [comment]
+1 for tracking the detailed feature through the git issue. @rambohe-ch @Fei-Guo, what do you think?

**Comment by Fei-Guo** [comment]
Thanks for the suggestion. Sure, the feature owners will create issues beforehand and ask for volunteers. We usually don't set a goal that needs 6 month+ efforts because there are too many uncertainties and it is hard to track progress. Since the core openyurt architecture is already stable, most of the short term changes are going to be enhancement features like we have listed in the roadmap.  

In terms of long term plans, there are thoughts of enhancing openyurt with more platform features such as CI/CD, edge compute resource provisioning and so on, but nothing has been decided yet. It is certainly welcome for the community uses to speak up their own thoughts and requirements so that we can discuss them via github issues or community meetings.

**Comment by rambohe-ch** [comment]
@Walnux Thank you for kindly suggestion. I think the feature owners will create issues after tomorrow's community meeting(2.24), and details of feature will also be discussed. I'm looking forward to your coming to OpenYurt community meeting.

**Comment by yixingjia** [comment]
> +1 for tracking the detailed feature through the git issue.

May be we can start with this two features first.

Add Cloud Native IOT Device Management API definition.
Support IOT Device Management that comply with cloud native IOT API

We can later add our initial discussion to the issues.

**Comment by rambohe-ch** [comment]
> > +1 for tracking the detailed feature through the git issue.
> 
> May be we can start with this two features first.
> 
> Add Cloud Native IOT Device Management API definition.
> Support IOT Device Management that comply with cloud native IOT API
> 
> After create the issue, we can add our initial discussions to the thread.

@yixingjia +1 for two features take steps firstly.
