### ISSUE TITLE
[Question] Does openyurt work with K3S?

### ISSUE THREAD

**Issue by thomastvedt** [openyurtio/openyurt#240]
Hi, does openyurt work with K3S?

**Comment by charleszheng44** [comment]
Thanks for your interest in OpenYurt. We have not tried out using OpenYurt with K3S yet. Theoretically, if K3S supports all upstream K8S features, then OpenYurt should be able to work with it. However, I can foresee that there are several settings that may need to be tweaked like the `nodelifecycle` controller need to be turned off on the server, and the K3S agent needs to be restarted and connect to the YurtHub instead of the K3S server. (There may be more, these are two points in my mind now )

You are welcome to try it out, please let us know if you run into any problems.

**Comment by thomastvedt** [comment]
Thanks, we might test this out when we get some spare time 👍🏻  If we do, I'll let you know how it went :)

**Comment by rambohe-ch** [comment]
> Thanks, we might test this out when we get some spare time 👍🏻 If we do, I'll let you know how it went :)

@thomastvedt  Thank you for pay attention to OpenYurt, We are looking forward to your test result.

**Comment by jasine** [comment]
we have similar situation and hoping for official support of k3s
