### ISSUE TITLE
[Question] Node communication in edge senarios

### ISSUE THREAD

**Issue by joker-joker-joker** [openyurtio/openyurt#264]
CNI plugins such as flannel require that the network between nodes are reachable, but in edge scenarios, it often appears that edge nodes and cloud nodes belong to different local area networks, and the cloud nodes are generally assigned public network IP while edge nodes will not. In this scenario, how should we solve the communication problem between edge nodes and cloud nodes? Is it by extending the CNI to the edge node, or is it through traffic interception at the application layer or the transport layer? Does openyurt consider this scenario?
Thanks

**Comment by Fei-Guo** [comment]
It is not recommended to run your workload across cloud nodes and edge nodes due to the networking problem you mentioned. In OpenYurt, we introduce a concept of node pool where a group of edge nodes are defined and a UnitedDeployment workload to distribute workload Pods among the nodes in the node pool. Usually, CNI plugin like flannel should work in node pool. Hope this will help or let us know if you have more specific concerns.

**Comment by joker-joker-joker** [comment]
Thanks for you reply.
If it is in a node pool of a local area network, flannel can indeed work. However, there are still scenarios for edge-cloud collaboration, such as joint inference in some AI scenarios. It is impossible to assume that they are in a node pool in a local area network.

**Comment by Fei-Guo** [comment]
Note that cloud nodes have public IPs hence the edge->cloud communication usually works. I am assuming one can leverage this fact to push computational results from edge nodes to cloud nodes. If edge network and cloud network are completely isolated (bi-directionally),  I think reverse proxy supported by vendor may work but it is out of OpenYurt's scope. OpenYurt only installs tunnel service between cloud apiserver and edge node to proxy control plane traffic  (not the application data plane).

**Comment by joker-joker-joker** [comment]
OK. Thanks for the reply.
