### ISSUE TITLE
[Question] What is the DNS best practice in the OpenYurt edge cluster?

### ISSUE THREAD

**Issue by SataQiu** [openyurtio/openyurt#515]
At present, we have a variety of DNS resolution implementations:

1. Deploy CoreDNS DaemonSet with hostnetwork，and then configure the Kubelet flag `--cluster-dns=127.0.0.1`
    
![image](https://user-images.githubusercontent.com/9354727/136885835-f3c7934a-bbbe-4257-8a5f-341ea8e16796.png)

2. Deploy CoreDNS DaemonSet and YurtHub on all the cluster nodes, then enable CoreDNS service topology awareness by add annotation `openyurt.io/topologyKeys=kubernetes.io/hostname` into CoreDNS Service.
    
![image](https://user-images.githubusercontent.com/9354727/136885863-0eddbc1c-ab62-4074-9f4e-c8b52d674483.png)

3. Deploy NodeLocalDNS DaemonSet (nodelocaldns access kube-apiserver directly)
    
![image](https://user-images.githubusercontent.com/9354727/136885882-7ef0b5c7-6039-4096-bf6d-bd6caded7340.png)

The benefit of options 1 and 3 is that you do not need to deploy YurtHub on cloud nodes.

The benefit of option 2 is CoreDNS Pod can run in the Pod network and the topology awareness is supported on both cloud and edge.

The advantage of option 3 over option 1 is that there is no additional configuration of Kubelet and no need to modify the existing CoreDNS Deployment or DaemonSet in the system.

So what is the DNS best practice in the OpenYurt edge cluster?

**Comment by rambohe-ch** [comment]
@SataQiu Thank you for raising issue.

I think we can follow the best practice of CoreDNS community. CoreDNS is the up dns for nodeLocalDNS, and nodeLocalDNS is a daemon app for every node.
And in OpenYurt edge cluster, we can use YurtAppDaemon(plan to release in v0.6.0 @kadisi ) to deploy CoreDNS from NodePool level, and use DaemonSet to deploy nodeLocalDNS.

so, yurthub maybe need to deploy on both edge and cloud nodes.

**Comment by DrmagicE** [comment]
I think deploying apps is beyond the scope of `nodepool` controller, which should focus on managing node topology but not the applications on nodes. Any `nodepool` awareness application can be managed in the upper layer, by `YurtAppDaemon`, helm or other dedicated operators.  To deploy CoreDNS deployment, I think `YurtAppDaemon` is good enough.

**Comment by zzguang** [comment]
The key point is whether we treat CoreDNS as an ordinary user app.
IMHO, CoreDNS/ingress controller are system components and their requirements are somehow different with the end user apps. Take ingress controller as an example, it requires to deploy an ingress controller deployment and a service for a nodepool, besides, in order to support validating admission webhook, it also requires to deploy webhook related deployment/service/ValidatingWebhookConfiguration... on cloud side, if we implement it through YurtAppDaemon, YurtAppDaemon needs to support multi deployments/multi services/ValidatingWebhookConfiguration/..., which seems not a generic design from the perspective of YurtAppDaemon.
Therefore, we suggest to separate system components from the end user apps, YurtAppDaemon is only responsible for the end user apps, while the nodepool related system components are treated as nodepool native features and are implemented by enhancing current nodepool operator. Besides, for the users will never care about the deployment of these system components, it improves the ease of use for these features.

**Comment by rambohe-ch** [comment]
@Fei-Guo Do you have any comments about above discussions?

**Comment by rambohe-ch** [comment]
@Fei-Guo @gnunu @kadisi 
1. `YurtAppDaemon` should be focus on NodePool level workload, in spite of system components or pure application workloads.
2.  Workloads of system components(like ingress-controller) can be deployed by `YurtAppDaemon`, but configuration(like webhooks) can not be included in `YurtAppDaemon`, so we need to add an operator(include YurtAppDaemon and webhooks) to deploy some components(like ingress-controller).
3. How to use these operators by end users, through NodePool or YurtCluster need to discuss.
