### ISSUE TITLE
[Question] Does the current edge network CNI plugin only support flannel?

### ISSUE THREAD

**Issue by slm940208** [openyurtio/openyurt#924]
Does the current edge network CNI plugin only support flannel?

**Comment by rambohe-ch** [comment]
@slm940208 Thank you for raising issue. in fact, all of cni network solutions(like flannel, calico) are supported in OpenYurt because no modification has been made to Kubernetes. 

but use cni network solution directly in cloud-edge scenario, when network connection between cloud and edge offline, if cni network plugin restart for some reason(like node reboot), the edge network settings maybe can not recover because network plugin can not get metadata(like service, endpoints) from cloud.

**Comment by rambohe-ch** [comment]
@slm940208 and for flannel, we have made some optimization in order to solving the above problems. you can dive into the detail design here: https://openyurt.io/docs/user-manuals/network/edge-pod-network/

**Comment by slm940208** [comment]
@rambohe-ch Thank you for your reply. The current community only gives Flannel's modification scheme？

**Comment by Congrool** [comment]
Actually, in the aspect of edge-network, I think we can support calico through raven, see openyurtio/raven#38.

We mention #857 here, because we're checking if calico can run as it is when cloud-edge network breaks.
