### ISSUE TITLE
[feature request]improve service topology ability for yurthub

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#954]
**What would you like to be added**:
At present, only service traffic in cluster or NodePort traffic can support service topology ability because
yurthub can filter endpointslice resource for kube-proxy.
egress traffic from ingress will not support service topology ability if ingress controller works based on the
endpoints, because yurthub can not filter endpoints resource for annotated service.
so i think we need to make sure the service topology ability can support all kinds of traffic.

**Why is this needed**:
service topology ability can not supported by ingress controller that works based on the endpoints.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@zzguang please have some comments about this issue.

**Comment by zzguang** [comment]
Agree with @rambohe-ch to enhance the yurthub data filtering for endpoints with some background introduction:
1. Current upstream nginx ingress controller access services through endpoints instead of endpointslice.
2. YurtIngress is focusing on orchestrating nginx ingress controller to user specified nodepools.
3. When ingress controller in a nodepool tries to access a service through endpoints, yurthub will filter the nodepool specific endpoints for the service by default.
However, in conditions when users deploy an ingress controller to the cloud side manually, and users want to access a service through the ingress controller, the related service is cluster level instead of nodepool level,  so the current yurthub endpoints filtering mechanism can not meet this requirement.
Proposed solutions:
Solution 1:
1. Integrate yurthub endpoints filtering into service topology mechanism.
2. When users try to access a service through ingress controller, the default behavior is not to filter the nodepool specific endpoints.
3. If users want to access a service through ingress controller from specific nodepools, follow the service topology mechanism to add the related annotation for the service to leverage the yurthub endpoints filtering feature.
Solution 2:
Just add judgement in yurthub endpoints filter:  check if the yurthub hosted node is a cloud node, then it's not necessary to make the endpoints filtering operation. This solution seems less effort and continue to keep service unchanged with no service topology annotations.
I prefer to adopt solution 2 by now.

**Comment by rambohe-ch** [comment]
> Agree with @rambohe-ch to enhance the yurthub data filtering for endpoints with some background introduction: 1). Current upstream nginx ingress controller access services through endpoints instead of endpointslice. 2). YurtIngress is focusing on orchestrating nginx ingress controller to user specified nodepools. 3). When ingress controller in a nodepool tries to access a service through endpoints, yurthub will filter the nodepool specific endpoints for the service by default. However, in conditions when users deploy an ingress controller to the cloud side manually, and users want to access a service through the ingress controller, the related service is cluster level instead of nodepool level, so the current yurthub endpoints filtering mechanism can not meet this requirement. Proposed solutions: Solution 1: 1). Integrate yurthub endpoints filtering into service topology mechanism. 2). When users try to access a service through ingress controller, the default behavior is not to filter the nodepool specific endpoints. 3). If users want to access a service through ingress controller from specific nodepools, follow the service topology mechanism to add the related annotation for the service to leverage the yurthub endpoints filtering feature. Solution 2: Just add judgement in yurthub endpoints filter: check whether the yurthub working-mode is cloud, if yes, it's not necessary to make the endpoints filtering operation. This solution seems less effort and continue to keep services unchanged with no service topology annotation. I prefer to adopt solution 2 by now.

@zzguang Thanks for your reply. I think we should keep the consistency for service topology. no matter how to access service(internal cluster, or from cluster outside through ingress controller), service topology should have the same ability.
so maybe solution 1 is the correct way to reach the goal. 

yes, solution 2 is more simpler, but i think it's a temporary solution. maybe we will revise it in the future. 

and i will take over the feature to optimize service topology filter in the Yurthub and use solution 1 to implement it.

**Comment by zzguang** [comment]
@rambohe-ch , my previous opinion is:
1). If users access a service directly(clusterIP/nodePort/SLB), users can leverage the service topology feature by adding the annotation to the service.
2). If users access a service indirectly through the ingress controller, then ingress controller is responsible to select the proper service endpoints by yurthub endpoints filtering, users don't need to care about whether the service is annotated.
Indeed it seems not consistent for service access method(direct/indirect), if we want to unify them, solution 1 is okay for me.

**Comment by rambohe-ch** [comment]
> @rambohe-ch , my previous opinion is: 1). If users access a service directly(clusterIP/nodePort/SLB), users can leverage the service topology feature by adding the annotation to the service. 2). If users access a service indirectly through the ingress controller, then ingress controller is responsible to select the proper service endpoints by yurthub endpoints filtering, users don't need to care about whether the service is annotated. Indeed it seems not consistent for service access method(direct/indirect), if we want to unify them, solution 1 is okay for me.

@zzguang Thank you for replying, ok, i will go to fix this problem based on the solution 1.
